In [3]:
import pandas as pd
data=pd.read_json("students_data.json")
data
data[data["Student_ID"]>120]

,Student_ID,Name,Age,Gender,City,Course,Marks,Attendance,Study_Hours,Email,Phone,Join_Date,Fees_Paid,Status,Extra_Column
20,121,Aarav Sharma,20.0,Male,Delhi,Data Science,85.0,92.0,4.5,aarav@gmail.com,9876543210,2025-01-10,45000,Active,duplicate
21,122,Ritika Sharma,25.0,Female,Delhi,Data Science,105.0,110.0,15.0,ritika@gmail.com,9876543230,2025-02-01,45000,Active,wrong
22,123,Mohit Kumar,17.0,M,DELHI,Python,55.0,65.0,1.5,mohit@gmail.com,9876543231,2025-02-02,30000,active,abc
23,124,Simran Kaur,26.0,F,delhi,Machine Learning,88.0,89.0,4.2,simran@gmail.com,9876543232,2025-02-03,45000,Inactive,test
24,125,Raj Gupta,-5.0,Male,Delhi,Python,62.0,70.0,2.1,raj@gmail.com,9876543233,2025-02-04,30000,Active,temp
25,126,Poonam Roy,21.0,Female,Mumbai,Web Dev,79.0,85.0,3.5,poonam@gmail.com,9876543234,2025-02-05,40000,Active,xyz
26,127,Vivek Singh,22.0,Male,Mumbai,Web Development,79.0,85.0,3.5,vivek@gmail.com,9876543235,2025-02-05,40000,Active,abc
27,128,Neha Kapoor,22.0,Female,Mumbai,Data Science,89.0,91.0,4.8,neha@gmail.com,9876543219,2025-01-20,45000,Active,duplicate
28,129,Aditi Joshi,21.0,Female,Delhi,Data Science,88.0,93.0,4.4,ADITI@GMAIL.COM,9876543237,2025-02-07,45000,ACTIVE,test
29,130,Ramesh Kumar,23.0,Male,Patna,Python,72.0,78.0,3.0,ramesh@gmail.com,9876543238,2025-02-08,30000,active,temp

In [11]:
# filtering data using query (query returns copy not view)
data.query("Student_ID > 120 & Age >20")[["Name","Age",'Phone']]

#by python variable
var=120
data.query("Student_ID >@var & Age >20")[["Name","Age",'Phone']]

             Name   Age       Phone
21  Ritika Sharma  25.0  9876543230
23    Simran Kaur  26.0  9876543232
25     Poonam Roy  21.0  9876543234
26    Vivek Singh  22.0  9876543235
27    Neha Kapoor  22.0  9876543219
28    Aditi Joshi  21.0  9876543237
29   Ramesh Kumar  23.0  9876543238